#!/bin/tcsh
#PBS -N BigCreekRTry1a
#PBS -A UCSB0009
#PBS -l walltime=1:00:00
#PBS -q regular 
#PBS -j oe
#PBS -k eod
#PBS -m abe
#PBS -M mkenn@uw.edu
#PBS -l select=1:ncpus=36:ompthreads=9

### Set TMPDIR as recommended
setenv TMPDIR /glade/scratch/$USER/temp
mkdir -p $TMPDIR
###Load R module
module load R/4.0.2
###make sure libwmfire is accessed
export LD_LIBRARY_PATH=.

### Run the executable
